apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-frontend
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false   # le frontend n'a généralement pas besoin de parler à l'API K8s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-backend
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true  # à activer seulement si le backend appelle l'API K8s (ex: lire un ConfigMap dynamiquement)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-database
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false   # la DB n'a jamais besoin de parler à l'API K8s
